# Generated by Django 5.0.6 on 2024-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="number",
        ),
        migrations.AlterField(
            model_name="semester",
            name="number",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "I/I"),
                    ("2", "I/II"),
                    ("3", "II/I"),
                    ("4", "II/II"),
                    ("5", "III/I"),
                    ("6", "III/II"),
                    ("7", "IV/I"),
                    ("8", "IV/II"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
