# Generated by Django 5.0.6 on 2024-09-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_remove_batch_number_alter_semester_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="batch",
        ),
        migrations.CreateModel(
            name="BatchSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_month", models.CharField(blank=True, max_length=25, null=True)),
                ("end_month", models.CharField(blank=True, max_length=25, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.batch",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "semester",
                "verbose_name_plural": "semesters",
            },
        ),
        migrations.AlterField(
            model_name="studentinsemester",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="management.batchsemester",
            ),
        ),
    ]
