# Generated by Django 5.0.6 on 2024-09-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_remove_semester_batch_batchsemester_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchsemester",
            options={
                "verbose_name": "batchsemester",
                "verbose_name_plural": "batchsemesters",
            },
        ),
    ]
