# Generated by Django 5.0.6 on 2024-09-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_batchsemester_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="end_month",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="is_current",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="start_month",
        ),
    ]
