# Generated by Django 5.0.6 on 2024-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0005_remove_semester_end_month_remove_semester_is_current_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
