# Generated by Django 5.0.6 on 2024-09-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsubjectattendance",
            name="day",
            field=models.DateField(),
        ),
    ]
