# Generated by Django 5.0.6 on 2024-09-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_alter_studentsubjectattendance_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentinternalexamresult",
            options={
                "verbose_name": "subjectinternalexamresult",
                "verbose_name_plural": "subjectinternalexamresult",
            },
        ),
    ]
