# Generated by Django 5.0.6 on 2024-09-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_examsession_studentinternalexamresult_exam_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchsemester",
            name="is_current",
        ),
        migrations.AddField(
            model_name="studentinsemester",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
    ]
