# Generated by Django 5.0.6 on 2024-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_remove_batchsemester_is_current_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="symbol_number",
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="student/"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="student/"),
        ),
    ]
