# Generated by Django 5.0.6 on 2024-12-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_remove_student_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="teacher/"),
        ),
    ]
