# Generated by Django 5.0.6 on 2024-12-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
