# Generated by Django 5.0.6 on 2024-12-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0014_notice_is_new_notice_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
