# Generated by Django 5.0.6 on 2025-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0015_alter_student_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchsemester",
            name="is_running",
            field=models.BooleanField(default=False),
        ),
    ]
