# Generated by Django 5.0.6 on 2026-03-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(blank=True, default='', null=True, upload_to='uploads/logo/')),
                ('about_text', models.TextField(blank=True, null=True)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='uploads/website/brochure/')),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('registration', models.CharField(blank=True, max_length=255, null=True)),
                ('office_hourse', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('post_box', models.TextField(blank=True, null=True)),
                ('telephone', models.TextField(blank=True, null=True)),
                ('email_address', models.TextField(blank=True, null=True)),
                ('google_map', models.TextField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About College',
                'verbose_name_plural': 'About College',
            },
        ),
        migrations.CreateModel(
            name='AboutUsTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_line', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'aboutus timeline',
                'verbose_name_plural': 'aboutus timeline',
            },
        ),
        migrations.CreateModel(
            name='AboutUsWhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_line', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'aboutus why section',
                'verbose_name_plural': 'aboutus why section',
            },
        ),
        migrations.CreateModel(
            name='AcademicCourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'academiccoursetype',
                'verbose_name_plural': 'academiccoursetype',
            },
        ),
        migrations.CreateModel(
            name='AcademicIndustryPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Academic Industry Partnership',
                'verbose_name_plural': 'Academic Industry Partnership',
            },
        ),
        migrations.CreateModel(
            name='AcademicPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('about_program', models.CharField(blank=True, max_length=255, null=True)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='uploads/website/brochure/')),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('current_intake', models.CharField(blank=True, max_length=255, null=True)),
                ('total_seats', models.CharField(blank=True, max_length=255, null=True)),
                ('total_program_fee_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'academic program',
                'verbose_name_plural': 'academic program',
            },
        ),
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'academic sem',
                'verbose_name_plural': 'academic sem',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic year',
            },
        ),
        migrations.CreateModel(
            name='AccreditionAndPartnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/why/icon/')),
                ('order_priority', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'accredition and partnership',
                'verbose_name_plural': 'accredition and partnership',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_year', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_line', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'admission',
                'verbose_name_plural': 'admission',
            },
        ),
        migrations.CreateModel(
            name='CollegeChairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/chairman/')),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('post_name', models.CharField(blank=True, max_length=255, null=True)),
                ('text_message', models.TextField(blank=True, null=True)),
                ('video_message', models.FileField(blank=True, null=True, upload_to='uploads/website/chairman/message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'College Chairman',
                'verbose_name_plural': 'College Chairman',
            },
        ),
        migrations.CreateModel(
            name='EmploymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Faculty Category',
                'verbose_name_plural': 'Faculty Category',
            },
        ),
        migrations.CreateModel(
            name='FacultyDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Faculty Degree',
                'verbose_name_plural': 'Faculty Degree',
            },
        ),
        migrations.CreateModel(
            name='FacultyDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'FacultyDesignation',
                'verbose_name_plural': 'Faculty Designation',
            },
        ),
        migrations.CreateModel(
            name='FacultyExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Faculty Expertise',
                'verbose_name_plural': 'Faculty Expertise',
            },
        ),
        migrations.CreateModel(
            name='FacultyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Faculty Type',
                'verbose_name_plural': 'Faculty Type',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_line', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.FileField(blank=True, null=True, upload_to='uploads/website/bgimage/')),
                ('support_image', models.FileField(blank=True, null=True, upload_to='uploads/website/supportimage/')),
                ('support_icon', models.FileField(blank=True, null=True, upload_to='uploads/website/supporticon/')),
                ('call_to_action_1', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_2', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_3', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_4', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_5', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_6', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action_7', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='LifeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_line', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='uploads/website/life/video/')),
            ],
            options={
                'verbose_name': 'life section',
                'verbose_name_plural': 'life section',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/website/testimonial/')),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('saying', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='WhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_line', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'why section',
                'verbose_name_plural': 'why section',
            },
        ),
        migrations.CreateModel(
            name='AboutUsTimelineContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/aboutus/timeline/icon/')),
                ('order_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('tag_1', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_2', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_3', models.CharField(blank=True, max_length=255, null=True)),
                ('aboutus_timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.aboutustimeline')),
            ],
            options={
                'verbose_name': 'aboutus timeline content',
                'verbose_name_plural': 'aboutus timeline content',
            },
        ),
        migrations.CreateModel(
            name='AboutUsWhySectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/aboutus/why/icon/')),
                ('order_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('aboutus_why', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.aboutuswhysection')),
            ],
            options={
                'verbose_name': 'aboutus why section content',
                'verbose_name_plural': 'aboutus why section content',
            },
        ),
        migrations.CreateModel(
            name='AcademicIndustryPartnershipContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/ptnr/icon/')),
                ('order_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.academicindustrypartnership')),
            ],
            options={
                'verbose_name': 'Academic Industry Partnership Content',
                'verbose_name_plural': 'Academic Industry Partnership Content',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgramObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_text', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'academic program objectives',
                'verbose_name_plural': 'academic program objectives',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgramLabResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'Academic Program LabResource',
                'verbose_name_plural': 'Academic Program LabResource',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgramKeySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'academic program skill',
                'verbose_name_plural': 'academic program skill',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgramEntranceExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_text', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'academic program entrance exam',
                'verbose_name_plural': 'academic program entrance exam',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgramEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_text', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'academic program eligibility',
                'verbose_name_plural': 'academic program eligibility',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgramCareerProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_text', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'academic program career',
                'verbose_name_plural': 'academic program career',
            },
        ),
        migrations.AddField(
            model_name='academicindustrypartnership',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms'),
        ),
        migrations.CreateModel(
            name='AcademicFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/website/faculty/photo/')),
                ('faculty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
                ('faculty_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.facultydegree')),
                ('faculty_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.facultydesignation')),
                ('faculty_expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.facultyexpertise')),
                ('faculty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.facultytype')),
            ],
            options={
                'verbose_name': 'Academic Faculty',
                'verbose_name_plural': 'Academic Faculty',
            },
        ),
        migrations.CreateModel(
            name='AcademicCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('program_structure', models.FileField(blank=True, null=True, upload_to='uploads/website/academic/structure/')),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='uploads/website/academic/syllabus/')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'Academic Curriculum',
                'verbose_name_plural': 'Academic Curriculum',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgramScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_text', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'academic program scholarship',
                'verbose_name_plural': 'academic program scholarship',
            },
        ),
        migrations.CreateModel(
            name='AcademicFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fee_special_text', models.CharField(blank=True, max_length=255, null=True)),
                ('fee_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicyear')),
            ],
            options={
                'verbose_name': 'academic fee structure',
                'verbose_name_plural': 'academic fee structure',
            },
        ),
        migrations.CreateModel(
            name='AcademicCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('total_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/course/icon/')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.academiccoursetype')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicsemester')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicyear')),
            ],
            options={
                'verbose_name': 'Academic Course',
                'verbose_name_plural': 'Academic Course',
            },
        ),
        migrations.CreateModel(
            name='AboutPageAccreditionAndPartnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accredition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.accreditionandpartnership')),
            ],
            options={
                'verbose_name': 'aboutpage accredition and partnership',
                'verbose_name_plural': 'aboutpage accredition and partnership',
            },
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/why/icon/')),
                ('order_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.admission')),
            ],
            options={
                'verbose_name': 'admission step',
                'verbose_name_plural': 'admission step',
                'ordering': ['order_priority'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentProviderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.employmentprovider')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAssignedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academiccourse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicfaculty')),
            ],
            options={
                'verbose_name': 'Faculty Assigned Course',
                'verbose_name_plural': 'Faculty Assigned Course',
            },
        ),
        migrations.CreateModel(
            name='HomePageAccreditionAndPartnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accredition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.accreditionandpartnership')),
            ],
            options={
                'verbose_name': 'homepage accredition and partnership',
                'verbose_name_plural': 'homepage accredition and partnership',
            },
        ),
        migrations.CreateModel(
            name='LabResourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/lab/icon/')),
                ('order_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('academic_lab_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.academicprogramlabresource')),
            ],
            options={
                'verbose_name': 'Lab Resource Content',
                'verbose_name_plural': 'Lab Resource Content',
            },
        ),
        migrations.CreateModel(
            name='LabResourceFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_resource_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.labresourcecontent')),
            ],
        ),
        migrations.CreateModel(
            name='LifeSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/why/icon/')),
                ('order_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('life_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.lifesection')),
            ],
            options={
                'verbose_name': 'life section content',
                'verbose_name_plural': 'life section content',
            },
        ),
        migrations.CreateModel(
            name='ProgramFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'program FAQ',
                'verbose_name_plural': 'program FAQ',
            },
        ),
        migrations.CreateModel(
            name='WhyAcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_text', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.academicprograms')),
            ],
            options={
                'verbose_name': 'why program',
                'verbose_name_plural': 'why program',
            },
        ),
        migrations.CreateModel(
            name='WhySectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('support_text', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/website/why/')),
                ('icon', models.FileField(blank=True, null=True, upload_to='uploads/website/why/icon/')),
                ('order_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('why_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.whysection')),
            ],
            options={
                'verbose_name': 'why section content',
                'verbose_name_plural': 'why section content',
            },
        ),
    ]
