# Generated by Django 5.0.6 on 2025-12-06 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="steps",
        ),
        migrations.AddField(
            model_name="admissionstep",
            name="admission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.admission",
            ),
        ),
    ]
