# Generated by Django 5.0.6 on 2025-12-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_remove_admission_steps_admissionstep_admission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicprogramobjectives",
            options={
                "verbose_name": "academic program objectives",
                "verbose_name_plural": "academic program objectives",
            },
        ),
        migrations.AlterModelOptions(
            name="admissionstep",
            options={
                "ordering": ["order_priority"],
                "verbose_name": "admission step",
                "verbose_name_plural": "admission step",
            },
        ),
        migrations.RemoveField(
            model_name="aboutustimeline",
            name="contents",
        ),
        migrations.RemoveField(
            model_name="aboutuswhysection",
            name="contents",
        ),
        migrations.RemoveField(
            model_name="employmentprovider",
            name="name",
        ),
        migrations.RemoveField(
            model_name="lifesection",
            name="contents",
        ),
        migrations.RemoveField(
            model_name="whysection",
            name="contents",
        ),
        migrations.AddField(
            model_name="aboutustimelinecontent",
            name="aboutus_timeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.aboutustimeline",
            ),
        ),
        migrations.AddField(
            model_name="aboutuswhysectioncontent",
            name="aboutus_why",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.aboutuswhysection",
            ),
        ),
        migrations.AddField(
            model_name="academicprograms",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employmentprovidername",
            name="employment_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.employmentprovider",
            ),
        ),
        migrations.AddField(
            model_name="lifesectioncontent",
            name="life_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.lifesection",
            ),
        ),
        migrations.AddField(
            model_name="whysectioncontent",
            name="why_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.whysection",
            ),
        ),
    ]
