# Generated by Django 5.0.6 on 2025-12-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_academicprogramobjectives_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicfeestructure",
            name="grand_total",
        ),
        migrations.RemoveField(
            model_name="academicfeestructure",
            name="notice",
        ),
        migrations.RemoveField(
            model_name="labresourcecontent",
            name="features",
        ),
        migrations.AddField(
            model_name="labresourcefeatures",
            name="lab_resource_content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.labresourcecontent",
            ),
        ),
    ]
