# Generated by Django 5.0.6 on 2025-12-07 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_remove_academicfeestructure_grand_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicprogramlabresource",
            name="lab_resource",
        ),
        migrations.AddField(
            model_name="labresourcecontent",
            name="academic_lab_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.academicprogramlabresource",
            ),
        ),
    ]
