# Generated by Django 5.0.6 on 2025-12-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_remove_academicprogramlabresource_lab_resource_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicindustrypartnership",
            name="content",
        ),
        migrations.AddField(
            model_name="academicindustrypartnershipcontent",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.academicindustrypartnership",
            ),
        ),
    ]
