# Generated by Django 5.0.6 on 2025-12-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_remove_academicindustrypartnership_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicfaculty",
            name="photo",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/website/faculty/photo/"
            ),
        ),
    ]
