# Generated by Django 5.0.6 on 2025-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_academicfaculty_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="support_icon",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/website/supporticon/"
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="support_image",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/website/supportimage/"
            ),
        ),
    ]
