# Generated by Django 5.0.6 on 2025-12-25 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_herosection_support_icon_herosection_support_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicCourseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "academiccoursetype",
                "verbose_name_plural": "academiccoursetype",
            },
        ),
        migrations.AddField(
            model_name="academiccourse",
            name="course_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.academiccoursetype",
            ),
        ),
    ]
