# Generated by Django 5.0.6 on 2025-12-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_academiccoursetype_academiccourse_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutcollege",
            name="office_hourse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
