# Generated by Django 5.0.6 on 2025-12-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_aboutcollege_office_hourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeChairman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/chairman/"
                    ),
                ),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_name", models.CharField(blank=True, max_length=255, null=True)),
                ("text_message", models.TextField(blank=True, null=True)),
                (
                    "video_message",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/website/chairman/message",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "College Chairman",
                "verbose_name_plural": "College Chairman",
            },
        ),
    ]
