# Generated by Django 5.0.6 on 2024-07-07 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("userprofile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userprofile.usertype"
            ),
        ),
        migrations.AddField(
            model_name="studentbatch",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.batch",
            ),
        ),
        migrations.AddField(
            model_name="studentbatch",
            name="student",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.student",
            ),
        ),
        migrations.AddField(
            model_name="studentyearlyscheduler",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yearlyschedules_student",
                to="dashboard.student",
            ),
        ),
        migrations.AddField(
            model_name="practicalinternalmarks",
            name="student_yearly_scheduler",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.studentyearlyscheduler",
            ),
        ),
        migrations.AddField(
            model_name="subjectschedule",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.schedule"
            ),
        ),
        migrations.AddField(
            model_name="subjectschedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.subject"
            ),
        ),
        migrations.AddField(
            model_name="practicalinternalmarks",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.subjectschedule",
            ),
        ),
        migrations.AddField(
            model_name="theoryinternalmarks",
            name="student_yearly_scheduler",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.studentyearlyscheduler",
            ),
        ),
        migrations.AddField(
            model_name="theoryinternalmarks",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.subjectschedule",
            ),
        ),
        migrations.AddField(
            model_name="yearlyscheduler",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.schedule"
            ),
        ),
        migrations.AddField(
            model_name="studentyearlyscheduler",
            name="yearly_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yearlyschedules_schedule",
                to="dashboard.yearlyscheduler",
            ),
        ),
    ]
