# Generated by Django 5.0.6 on 2024-06-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsbatch",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="practicalinternalmarks",
            name="student",
        ),
        migrations.RemoveField(
            model_name="practicalinternalmarks",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="publication",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user_type",
        ),
        migrations.RemoveField(
            model_name="studentyearlyschedule",
            name="student",
        ),
        migrations.RemoveField(
            model_name="theoryinternalmarks",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentsbatch",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentyearlyschedule",
            name="yearly_schedule",
        ),
        migrations.RemoveField(
            model_name="subjectyearlyschedule",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="subjectyearlyschedule",
            name="yearly_schedule",
        ),
        migrations.RemoveField(
            model_name="theoryinternalmarks",
            name="subject",
        ),
        migrations.DeleteModel(
            name="Batch",
        ),
        migrations.DeleteModel(
            name="PracticalInternalMarks",
        ),
        migrations.DeleteModel(
            name="Publication",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="StudentsBatch",
        ),
        migrations.DeleteModel(
            name="StudentYearlySchedule",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="YearlySchedule",
        ),
        migrations.DeleteModel(
            name="SubjectYearlySchedule",
        ),
        migrations.DeleteModel(
            name="TheoryInternalMarks",
        ),
    ]
