# Generated by Django 5.0.6 on 2024-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0002_remove_studentsbatch_batch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Yearly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "month_from_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("year_part", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "semester_part",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "remarks",
                    models.CharField(blank=True, default="", max_length=5, null=True),
                ),
            ],
        ),
    ]
