# Generated by Django 5.0.6 on 2024-06-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_batch_practicalinternalmarks_publication_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearlyschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="yearlyschedule",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="yearlyschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
