# Generated by Django 5.0.6 on 2024-06-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0005_yearlyschedule_created_at_yearlyschedule_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentyearlyschedule",
            name="student",
            field=models.ManyToManyField(
                related_name="studentyearlyschedules", to="dashboard.student"
            ),
        ),
        migrations.CreateModel(
            name="StudentYearlyScheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearlyschedules_student",
                        to="dashboard.student",
                    ),
                ),
                (
                    "yearly_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearlyschedules_schedule",
                        to="dashboard.yearlyschedule",
                    ),
                ),
            ],
        ),
    ]
