# Generated by Django 5.0.6 on 2024-06-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_student_user_delete_studentyearlyschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentyearlyscheduler",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="studentyearlyscheduler",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="studentyearlyscheduler",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
