# Generated by Django 5.0.6 on 2024-07-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sliderhome",
            name="content",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
