# Generated by Django 5.0.6 on 2024-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/cover/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cover Image",
                "verbose_name_plural": "Cover Images",
            },
        ),
    ]
