# Generated by Django 5.0.6 on 2024-07-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_alter_sliderhome_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sliderhome",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
