# Generated by Django 5.0.6 on 2024-06-09 06:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "why_biomedical",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="why_biomedical"
                    ),
                ),
                (
                    "why_photo",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/image/"
                    ),
                ),
            ],
        ),
    ]
