# Generated by Django 5.0.6 on 2024-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "feature_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "feature_img",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/feat/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="home",
            name="features",
            field=models.ManyToManyField(blank=True, default="", to="general.feature"),
        ),
    ]
