# Generated by Django 5.0.6 on 2024-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_alter_sliderhome_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="about_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="email_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="google_map",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="post_box",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="telephone",
            field=models.TextField(blank=True, null=True),
        ),
    ]
