# Generated by Django 5.0.6 on 2024-06-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0005_feature_home_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="noticeandresult",
            name="display_as_new",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="noticeandresult",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vaccancy",
            name="display_as_new",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="vaccancy",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
