# Generated by Django 5.0.6 on 2024-07-08 12:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0005_alter_aboutus_about_text_alter_aboutus_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="about_text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="about_text"
            ),
        ),
    ]
