# Generated by Django 5.0.6 on 2024-07-07 21:32

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0005_entrancesyllabus"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligiblityCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="eligiblity content"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/eligiblity/pdf/"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Eligiblity Criteria",
                "verbose_name_plural": "Eligiblity Criteria",
            },
        ),
        migrations.AlterModelOptions(
            name="entrancesyllabus",
            options={
                "verbose_name": "Entrance Syllabus",
                "verbose_name_plural": "Entrance Syllabus",
            },
        ),
    ]
