# Generated by Django 5.0.6 on 2024-07-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0006_eligiblitycriteria_alter_entrancesyllabus_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="first_name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="contactmessage",
            old_name="last_name",
            new_name="subject",
        ),
    ]
