# Generated by Django 5.0.6 on 2024-06-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0006_news_slug_noticeandresult_display_as_new_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user_type",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="StudentBatch",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
