# Generated by Django 5.0.6 on 2024-07-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_testimonial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name": "Staff", "verbose_name_plural": "Staff"},
        ),
        migrations.AlterModelOptions(
            name="stafftype",
            options={
                "verbose_name": "Staff Type",
                "verbose_name_plural": "Staff Types",
            },
        ),
        migrations.RenameField(
            model_name="chairman",
            old_name="faculty",
            new_name="staff",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="faculty_type",
            new_name="staff_type",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="user",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="user_type",
        ),
        migrations.AddField(
            model_name="staff",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
