# Generated by Django 5.0.6 on 2024-07-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_rename_first_name_contactmessage_full_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_1", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_1",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/slider/image/"
                    ),
                ),
                ("title_2", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_2",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/slider/image/"
                    ),
                ),
                ("title_3", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_3",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/slider/image/"
                    ),
                ),
                ("title_4", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_4",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/slider/image/"
                    ),
                ),
                ("title_5", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_5",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/slider/image/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Home Slider",
                "verbose_name_plural": "Home Slider",
            },
        ),
    ]
