# Generated by Django 5.0.6 on 2024-06-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_remove_student_batch_remove_student_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionPartners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/partners/"
                    ),
                ),
            ],
        ),
    ]
