# Generated by Django 5.0.6 on 2024-07-08 06:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0008_homeslider"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslider",
            name="content_1",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="content_1"
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="content_2",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="content_2"
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="content_3",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="content_3"
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="content_4",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="content_4"
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="content_5",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="content_5"
            ),
        ),
    ]
