# Generated by Django 5.0.6 on 2024-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0008_alter_staff_options_alter_stafftype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="job_type",
            field=models.TextField(
                blank=True, choices=[("1", "full time"), ("2", "visiting")], null=True
            ),
        ),
    ]
