# Generated by Django 5.0.6 on 2024-07-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0009_staff_job_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video Testimonial",
                "verbose_name_plural": "Video Testimonials",
            },
        ),
    ]
