# Generated by Django 5.0.6 on 2024-07-08 06:36

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0009_homeslider_content_1_homeslider_content_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/home/slider/image/"
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="content_1"
                    ),
                ),
            ],
            options={
                "verbose_name": "Slider Home",
                "verbose_name_plural": "Slider Home",
            },
        ),
        migrations.DeleteModel(
            name="HomeSlider",
        ),
    ]
