# Generated by Django 5.0.6 on 2024-07-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0010_videotestimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videotestimonial",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="videotestimonial",
            name="profession",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
