# Generated by Django 5.0.6 on 2024-07-13 15:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0011_videotestimonial_name_videotestimonial_profession"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeChairman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/chairman/"
                    ),
                ),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "message",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "College Chairman",
                "verbose_name_plural": "College Chairman",
            },
        ),
        migrations.DeleteModel(
            name="Chairman",
        ),
    ]
