# Generated by Django 5.0.6 on 2024-07-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0012_collegechairman_delete_chairman"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="order_priority",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="sliderhome",
            name="order_priority",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="order_priority",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
