# Generated by Django 5.0.6 on 2024-07-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0013_feature_order_priority_sliderhome_order_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="video_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
