# Generated by Django 5.0.6 on 2024-07-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0014_aboutus_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="feature_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
