# Generated by Django 5.0.6 on 2024-07-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0015_alter_feature_feature_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="redirect_to_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="scroll",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notice",
            name="redirect_to_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="scroll",
            field=models.BooleanField(default=False),
        ),
    ]
