# Generated by Django 5.0.6 on 2024-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0016_news_redirect_to_url_news_scroll_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=1255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("batch", models.CharField(blank=True, max_length=15, null=True)),
                ("department", models.CharField(max_length=150)),
                ("current_position", models.CharField(max_length=150)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "current_occupation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("achievements", models.TextField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="A message or advice from the alumni.",
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="alumni_pictures/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Alumni",
                "ordering": ["batch", "full_name"],
            },
        ),
    ]
