# Generated by Django 5.0.6 on 2024-12-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0017_alumni"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
