# Generated by Django 5.0.6 on 2025-06-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0019_modalimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/boardmember/"
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "order_priority",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "board_members",
                "verbose_name_plural": "board_members",
            },
        ),
    ]
