# Generated by Django 5.0.6 on 2025-11-04 14:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0020_boardmembers"),
        (
            "student_management",
            "0010_remove_studentinternalexamresult_marks_obtained_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("established_date", models.DateField()),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="description"),
                ),
                (
                    "head_of_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.teacher",
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.syllabus",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentAlumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="general.alumni"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DepartmentAlumnies",
            },
        ),
        migrations.CreateModel(
            name="DepartmentGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.department",
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.gallery",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DepartmentGalleries",
            },
        ),
        migrations.CreateModel(
            name="DepartmentTeachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.department",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DepartmentTeachers",
            },
        ),
    ]
