# Generated by Django 5.0.6 on 2025-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0021_department_departmentalumni_departmentgallery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
