# Generated by Django 5.0.6 on 2025-11-06 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0022_department_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="syllabus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="general.syllabus",
            ),
        ),
    ]
