# Generated by Django 5.0.6 on 2025-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="returned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
