# Generated by Django 5.0.6 on 2024-09-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="appuser",
            name="usertype",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.usertype",
            ),
        ),
    ]
