# Generated by Django 5.0.6 on 2024-09-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofile",
            "0002_remove_appuser_first_name_remove_appuser_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="usertype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.usertype",
            ),
        ),
    ]
