# Generated by Django 5.0.6 on 2024-09-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppUser",
        ),
        migrations.DeleteModel(
            name="UserType",
        ),
    ]
