# Generated by Django 5.0.6 on 2026-03-26 13:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'academic_batch',
                'verbose_name_plural': 'academic_batch',
            },
        ),
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, choices=[('1', 'I/I'), ('2', 'I/II'), ('3', 'II/I'), ('4', 'II/II'), ('5', 'III/I'), ('6', 'III/II'), ('7', 'IV/I'), ('8', 'IV/II')], max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'academic_semester',
                'verbose_name_plural': 'academic_semesters',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'degree',
                'verbose_name_plural': 'degree',
            },
        ),
        migrations.CreateModel(
            name='ExternalExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('examination_held_on', models.CharField(blank=True, max_length=255, null=True)),
                ('year_semester', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=255, null=True)),
                ('result_published_date', models.CharField(blank=True, max_length=255, null=True)),
                ('result_record', models.FileField(blank=True, null=True, upload_to='external/result/')),
                ('original_result_record', models.FileField(blank=True, null=True, upload_to='external/result/original/')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'external_exam_type',
                'verbose_name_plural': 'external_exam_type',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'section',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'university',
            },
        ),
        migrations.CreateModel(
            name='BatchSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.academicsemester')),
            ],
            options={
                'verbose_name': 'batch_semester',
                'verbose_name_plural': 'batch_semesters',
            },
        ),
        migrations.CreateModel(
            name='BatchSemesterNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('messages', models.TextField(blank=True, default='', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='semester/notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('batch_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.batchsemester')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_degree_academic_batch', to='student_management.academicbatch')),
            ],
            options={
                'verbose_name': 'degree_batch',
                'verbose_name_plural': 'degree_batch',
            },
        ),
        migrations.AddField(
            model_name='batchsemester',
            name='degree_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.degreebatch'),
        ),
        migrations.CreateModel(
            name='DegreeSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.academicsemester')),
            ],
            options={
                'verbose_name': 'degree_semester',
                'verbose_name_plural': 'degree_semester',
            },
        ),
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='subject/syllabus/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('degree_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.degreesemester')),
            ],
            options={
                'verbose_name': 'academic_subject',
                'verbose_name_plural': 'academic_subject',
            },
        ),
        migrations.CreateModel(
            name='ExternalExamResultContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_number', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sgpa', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_fail', models.CharField(blank=True, max_length=255, null=True)),
                ('result_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.externalexamresult')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalExamResultScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('external_result_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.externalexamresultcontent')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='student/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'students',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(blank=True, null=True, upload_to='subject/attendance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.academicsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
            options={
                'verbose_name': 'student_subject_attendance',
                'verbose_name_plural': 'student_subject_attendance',
            },
        ),
        migrations.CreateModel(
            name='StudentBatchSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.batchsemester')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
            options={
                'verbose_name': 'student_batch_semester',
                'verbose_name_plural': 'student_batch_semester',
            },
        ),
        migrations.CreateModel(
            name='StudentGradeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_sheet', models.FileField(blank=True, null=True, upload_to='student/gradesheet/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_batch_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.studentbatchsemester')),
            ],
            options={
                'verbose_name': 'student_gradesheet',
                'verbose_name_plural': 'student_gradesheet',
            },
        ),
        migrations.CreateModel(
            name='StudentInternalExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(blank=True, null=True, upload_to='internal/exam/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.academicsubject')),
                ('batch_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.batchsemester')),
            ],
            options={
                'verbose_name': 'student_internalexam_result',
                'verbose_name_plural': 'student_internalexam_result',
            },
        ),
        migrations.CreateModel(
            name='StudentInternalExamResultContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_batch_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.studentbatchsemester')),
                ('student_internalexam_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.studentinternalexamresult')),
            ],
            options={
                'verbose_name': 'student_internalexam_result_content',
                'verbose_name_plural': 'student_internalexam_content',
            },
        ),
        migrations.CreateModel(
            name='SubjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.academicsubject')),
                ('batch_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.batchsemester')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.section')),
            ],
            options={
                'verbose_name': 'subject_attendance',
                'verbose_name_plural': 'subject_attendance',
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_batch_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.studentbatchsemester')),
                ('subject_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.subjectattendance')),
            ],
            options={
                'verbose_name': 'student_subject_attendance',
                'verbose_name_plural': 'student_subject_attendance',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=25, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='teacher/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teachers',
                'verbose_name_plural': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.academicsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.teacher')),
            ],
            options={
                'verbose_name': 'subject_teacher',
                'verbose_name_plural': 'subject_teacher',
            },
        ),
        migrations.CreateModel(
            name='UniversityDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_degree', to='student_management.degree')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_university', to='student_management.university')),
            ],
            options={
                'verbose_name': 'universitydegree',
                'verbose_name_plural': 'universitydegree',
            },
        ),
        migrations.AddField(
            model_name='degreesemester',
            name='university_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_degree_semester', to='student_management.universitydegree'),
        ),
        migrations.AddField(
            model_name='degreebatch',
            name='university_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_degree_batch', to='student_management.universitydegree'),
        ),
    ]
