# Generated by Django 5.0.6 on 2025-03-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "examination_held_on",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "year_semester",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("exam_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "result_published_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "result_record",
                    models.FileField(
                        blank=True, null=True, upload_to="external/result/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalExamResultContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sgpa", models.CharField(blank=True, max_length=255, null=True)),
                ("pass_fail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "result_meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.externalexamresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalExamResultScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("score", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "external_result_content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.externalexamresultcontent",
                    ),
                ),
            ],
        ),
    ]
