# Generated by Django 5.0.6 on 2025-03-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
