# Generated by Django 5.0.6 on 2025-03-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0002_teacher_designation_teacher_education"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsubjectattendance",
            name="student",
        ),
        migrations.AddField(
            model_name="studentsubjectattendance",
            name="student_batch_semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management.studentbatchsemester",
            ),
        ),
        migrations.AlterField(
            model_name="studentsubjectattendance",
            name="academic_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management.academicsubject",
            ),
        ),
    ]
