# Generated by Django 5.0.6 on 2025-03-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0003_externalexamresult_original_result_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchSemesterNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages", models.TextField(blank=True, default="", null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="semester/notices/"
                    ),
                ),
                (
                    "batch_semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.batchsemester",
                    ),
                ),
            ],
        ),
    ]
