# Generated by Django 5.0.6 on 2025-03-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0003_remove_studentsubjectattendance_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.academicsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject_attendance",
                "verbose_name_plural": "subject_attendance",
            },
        ),
        migrations.CreateModel(
            name="StudentSubjectAttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student_batch_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.studentbatchsemester",
                    ),
                ),
                (
                    "subject_attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.subjectattendance",
                    ),
                ),
            ],
            options={
                "verbose_name": "student_subject_attendance",
                "verbose_name_plural": "student_subject_attendance",
            },
        ),
        migrations.DeleteModel(
            name="StudentSubjectAttendance",
        ),
    ]
