# Generated by Django 5.0.6 on 2025-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0004_batchsemesternotice"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchsemesternotice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="batchsemesternotice",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="batchsemesternotice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
