# Generated by Django 5.0.6 on 2025-03-28 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_management",
            "0004_subjectattendance_studentsubjectattendancerecord_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectattendance",
            name="batch_semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management.batchsemester",
            ),
        ),
    ]
