# Generated by Django 5.0.6 on 2025-03-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0005_batchsemesternotice_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchsemesternotice",
            name="title",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
