# Generated by Django 5.0.6 on 2025-03-31 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0005_subjectattendance_batch_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGradeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_sheet",
                    models.FileField(
                        blank=True, null=True, upload_to="student/gradesheet/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student_batch_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.studentbatchsemester",
                    ),
                ),
            ],
            options={
                "verbose_name": "student_gradesheet",
                "verbose_name_plural": "student_gradesheet",
            },
        ),
    ]
