# Generated by Django 5.0.6 on 2025-05-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0007_section_studentbatchsemester_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectattendance",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management.section",
            ),
        ),
    ]
