# Generated by Django 5.0.6 on 2025-05-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0008_subjectattendance_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInternalExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks_obtained",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "record",
                    models.FileField(blank=True, null=True, upload_to="internal/exam/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.academicsubject",
                    ),
                ),
                (
                    "student_batch_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.studentbatchsemester",
                    ),
                ),
            ],
            options={
                "verbose_name": "student_internalexam_result",
                "verbose_name_plural": "student_internalexam_result",
            },
        ),
    ]
