# Generated by Django 5.0.6 on 2025-05-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0009_studentinternalexamresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentinternalexamresult",
            name="marks_obtained",
        ),
        migrations.RemoveField(
            model_name="studentinternalexamresult",
            name="student_batch_semester",
        ),
        migrations.AddField(
            model_name="studentinternalexamresult",
            name="batch_semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management.batchsemester",
            ),
        ),
        migrations.CreateModel(
            name="StudentInternalExamResultContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks_obtained",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student_batch_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.studentbatchsemester",
                    ),
                ),
                (
                    "student_internalexam_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management.studentinternalexamresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "student_internalexam_result_content",
                "verbose_name_plural": "student_internalexam_content",
            },
        ),
    ]
