# Generated by Django 5.0.6 on 2025-11-06 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_management",
            "0010_remove_studentinternalexamresult_marks_obtained_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchsemester",
            name="end_month",
        ),
        migrations.RemoveField(
            model_name="batchsemester",
            name="start_month",
        ),
        migrations.AddField(
            model_name="batchsemester",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="batchsemester",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
